---
title: "CV"
---

# Mohammadsobhan Esfandiar

## Research Interests
- Human Robot Interaction
- AR/VR in Robotics
- Physical Interaction Design
- Social Psychology in HRI

## Awards & Honors
- Fully funded SGSSS scholarship for a 1+3 MSc and PhD program at the University of Glasgow
- IYT (Invest your talent in Italy) Scholarship (2022-2024)
- Grant for studies from Iran's National Elites Foundation (2014, 2016, 2017)
- Ranked 231st in Iranian University Entrance Exam among 222,000 participants (2013)
- Silver medal of the 26th Iranian National Physics Olympiad (2012)

## Languages
- English (Fluent)
- Italian (Intermediate)
- Persian (Native)

## Skills
**Expert:**
- SOLIDWORKS, Inventor AutoCAD, Ansys mechanical, MATLAB, Word, Excel, PowerPoint, Granta Edu Pack, ARDUINO, 3D printing

**Intermediate:**
- CATIA, Keyshot, Abaqus, Unity, C++ programming, Adobe Photoshop, Adobe Illustrator, Adobe InDesign

## Education
**University of Glasgow** (2024 - now)
- MSc in Research Methods of Psychological Science
- PhD in Social Touch in Physical Human Robot Interaction

**Politecnico di Milano** (2022 - 2024)
- MSc in Design and Engineering (GPA=28.5/30) – Mark = 109/110
- Ambassador in Smart Infrastructures
- Thesis title: The Room: design of a space as a social being - a speculative approach

**Sharif University of Technology** (2014 - 2018)
- BSc in Mechanical Engineering (GPA=17.38/20)
- Minor in Industrial Design
- Thesis title: Design variables’ tolerances effects on modal characteristics of a Governor mechanism in dynamic equilibrium

## Work Experience
**Nuzoo Robotics – Industrial Designer and Project Engineer** (Feb. 2024 – April 2024, Italy)
- Designed a new payload system for surveillance mobile robots using Inventor.
- Analyzed available VR cameras in the market for use in mobile robots.
- Researched the use of 3D scanners in an inspection climber robot.
- Rendered a mobile robot for presentation in websites and brochures.

**FAS - Technical Project Manager** (2020 – 2022, Iran)
- Participated in creating a part number system for designed and produced parts.
- Utilized rapid prototyping such as FDM, SLS, SLM, and vacuum casting in design and production processes.

**FAS - Mechatronic Engineer** (2018 – 2020, Iran)
- Designed and developed aerial imagery systems with 3 or 2 axis gimbal and passive vibration absorber.
- Developed passive vibration absorbers with wire rope dampers and rubber dampers.
- Analyzed and utilized various cooling methods in mechatronic systems design.
- Utilized low-cogging BLDC motors for higher precision gimbals.

**NODET Schools - Physics Teacher** (Sep. 2014 – July 2017)
- Provided comprehensive math and physics lessons to prepare high-school students for the Physics Olympiad.